# Generated by Django 4.1.3 on 2022-11-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='order',
        ),
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'RED'), ('green', 'GREEN'), ('white', 'WHITE')], max_length=6, null=True),
        ),
        migrations.DeleteModel(
            name='CardDetails',
        ),
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
